IronPython 2.7.7 (2.7.7.0) on .NET 4.0.30319.42000 (64-bit)
Type "help", "copyright", "credits" or "license" for more information.
>>> wc = DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_Walls).WhereElementIsNotElementType().ToElements()
>>> print wc
﻿List[Element]([<Autodesk.Revit.DB.Wall object at 0x0000000000000316 [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x0000000000000317 [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x0000000000000318 [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x0000000000000319 [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x000000000000031A [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x000000000000031B [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x000000000000031C [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x000000000000031D [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x000000000000031E [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x000000000000031F [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x0000000000000320 [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x0000000000000321 [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x0000000000000322 [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x0000000000000323 [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x0000000000000324 [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x0000000000000325 [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x0000000000000326 [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x0000000000000327 [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x0000000000000328 [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x0000000000000329 [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x000000000000032A [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x000000000000032B [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x000000000000032C [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x000000000000032D [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x000000000000032E [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x000000000000032F [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x0000000000000330 [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x0000000000000331 [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x0000000000000332 [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x0000000000000333 [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x0000000000000334 [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x0000000000000335 [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x0000000000000336 [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x0000000000000337 [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x0000000000000338 [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x0000000000000339 [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x000000000000033A [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x000000000000033B [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x000000000000033C [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x000000000000033D [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x000000000000033E [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x000000000000033F [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x0000000000000340 [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x0000000000000341 [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x0000000000000342 [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x0000000000000343 [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x0000000000000344 [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x0000000000000345 [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x0000000000000346 [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x0000000000000347 [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x0000000000000348 [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x0000000000000349 [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x000000000000034A [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x000000000000034B [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x000000000000034C [Autodesk.Revit.DB.Wall]>, <Autodesk.Revit.DB.Wall object at 0x000000000000034D [Autodesk.Revit.DB.Wall]>])
>>> wc = DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_Walls).WhereElementIsNotElementType()
>>> print wc
<Autodesk.Revit.DB.FilteredElementCollector object at 0x000000000000034E [Autodesk.Revit.DB.FilteredElementCollector]>
>>> wc = DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_Walls).WhereElementIsElementType().ToElements()
>>> print wc
List[Element]([<Autodesk.Revit.DB.WallType object at 0x000000000000034F [Autodesk.Revit.DB.WallType]>, <Autodesk.Revit.DB.WallType object at 0x0000000000000350 [Autodesk.Revit.DB.WallType]>, <Autodesk.Revit.DB.WallType object at 0x0000000000000351 [Autodesk.Revit.DB.WallType]>, <Autodesk.Revit.DB.WallType object at 0x0000000000000352 [Autodesk.Revit.DB.WallType]>, <Autodesk.Revit.DB.WallType object at 0x0000000000000353 [Autodesk.Revit.DB.WallType]>, <Autodesk.Revit.DB.WallType object at 0x0000000000000354 [Autodesk.Revit.DB.WallType]>, <Autodesk.Revit.DB.WallType object at 0x0000000000000355 [Autodesk.Revit.DB.WallType]>, <Autodesk.Revit.DB.WallType object at 0x0000000000000356 [Autodesk.Revit.DB.WallType]>, <Autodesk.Revit.DB.WallType object at 0x0000000000000357 [Autodesk.Revit.DB.WallType]>, <Autodesk.Revit.DB.WallType object at 0x0000000000000358 [Autodesk.Revit.DB.WallType]>, <Autodesk.Revit.DB.WallType object at 0x0000000000000359 [Autodesk.Revit.DB.WallType]>])
>>> wc = DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_Walls).WhereElementIsNotElementType().ToElements()
>>> len(wc)
56
>>> wc = DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_Walls).WhereElementIsElementType().ToElements()
>>> wc
List[Element]([<Autodesk.Revit.DB.WallType object at 0x000000000000035A [Autodesk.Revit.DB.WallType]>, <Autodesk.Revit.DB.WallType object at 0x000000000000035B [Autodesk.Revit.DB.WallType]>, <Autodesk.Revit.DB.WallType object at 0x000000000000035C [Autodesk.Revit.DB.WallType]>, <Autodesk.Revit.DB.WallType object at 0x000000000000035D [Autodesk.Revit.DB.WallType]>, <Autodesk.Revit.DB.WallType object at 0x000000000000035E [Autodesk.Revit.DB.WallType]>, <Autodesk.Revit.DB.WallType object at 0x000000000000035F [Autodesk.Revit.DB.WallType]>, <Autodesk.Revit.DB.WallType object at 0x0000000000000360 [Autodesk.Revit.DB.WallType]>, <Autodesk.Revit.DB.WallType object at 0x0000000000000361 [Autodesk.Revit.DB.WallType]>, <Autodesk.Revit.DB.WallType object at 0x0000000000000362 [Autodesk.Revit.DB.WallType]>, <Autodesk.Revit.DB.WallType object at 0x0000000000000363 [Autodesk.Revit.DB.WallType]>, <Autodesk.Revit.DB.WallType object at 0x0000000000000364 [Autodesk.Revit.DB.WallType]>])
>>> len(wc)
11

>>> [el.FamilyName for el in wc]
﻿['Basic Wall', 'Basic Wall', 'Basic Wall', 'Basic Wall', 'Basic Wall', 'Basic Wall', 'Curtain Wall', 'Basic Wall', 'Basic Wall', 'Basic Wall', 'Basic Wall']
>>> wc = DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_Walls).WhereElementIsElementType().ToElements()